ARG VERSION=12.3.3

FROM grafana/grafana-oss:${VERSION}

# Copy custom config for JSON logging
COPY grafana.ini /etc/grafana/grafana.ini

# Copy the datasources and dashboards
COPY datasources /etc/grafana/provisioning/datasources
