# Configuration file version
# See here fore more information on configuration:
# https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-configuration-file
apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
prune: false

# List of data sources to insert/update depending on what's available.
datasources:
  - name: Loki
    type: loki
    access: direct
    orgId: 1
    uid: grafana_lokiq
    url: $LOKI_INTERNAL_URL
    user:
    database:
    basicAuth:
    basicAuthUser:
    withCredentials:
    isDefault: true
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: $PROMETHEUS_INTERNAL_URL
    user:
    database:
    basicAuth:
    basicAuthUser:
    withCredentials:
    isDefault: false
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: grafana_tempo
    url: $TEMPO_INTERNAL_URL
    user:
    database:
    basicAuth:
    basicAuthUser:
    withCredentials:
    isDefault: false
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    url: redis://$REDISHOST:$REDISPORT
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
    secureJsonData:
      password: $REDIS_PASSWORD
  - name: MomentumBets Postgres
    type: postgres
    url: $POSTGRES_INTERNAL_URL
    user: mb_reporting
    secureJsonData:
      password: $REPORTING_PG_PASSWORD
    jsonData:
      database: postgres
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
apps:
  - name: Redis
    type: redis-app
    disabled: false
    orgId: 1
    uid: grafana_redis
